<div class="alert alert-block alert-danger">

 <b> Data load </b> 
</div>

import Libraries

In [1]:
import pandas as pd

<div class="alert alert-block alert-danger">

 <b> Data gathering </b> 
</div>

In [2]:
### data gathering
df = pd.read_csv('C:\\Users\\aimay\\OneDrive\\Desktop\\AI lab\\skin_care.csv')
df

,Unnamed: 0,price,title,stars,vote
0,0,6000,BeautyBio Rose Quartz Roller,4.7,75
1,1,2800,Kopari Starry Eye Balm,4.0,11
2,2,7200,StriVectin SuperC Brighten and Correct Serum,4.6,271
3,3,5900,Skin Gym Rose Quartz Facial Workout Set Nordst...,5.0,1
4,4,9150,Slip Marble and Charcoal Pillowcase and Sl...,5.0,2
...,...,...,...,...,...
3239,3239,12539,Origins GinZing UltraHydrating EnergyBoosting ...,4.6,8
3240,3240,18202,dermalogica PreCleanse Balm and Mitt,4.6,552
3241,3241,22247,Skin Inc Pure Serum Mist,4.9,11
3242,3242,27101,Clinique Repairwear Uplifting Firming Cream fo...,4.2,154
3243,3243,27101,Clinique Repairwear Uplifting Firming Cream fo...,4.2,276

<div class="alert alert-block alert-danger">

 <b> Data Analysis </b>
</div>

In [3]:
df.head()

,Unnamed: 0,price,title,stars,vote
0,0,6000,BeautyBio Rose Quartz Roller,4.7,75
1,1,2800,Kopari Starry Eye Balm,4.0,11
2,2,7200,StriVectin SuperC Brighten and Correct Serum,4.6,271
3,3,5900,Skin Gym Rose Quartz Facial Workout Set Nordst...,5.0,1
4,4,9150,Slip Marble and Charcoal Pillowcase and Sl...,5.0,2

In [4]:
df.tail()

,Unnamed: 0,price,title,stars,vote
3239,3239,12539,Origins GinZing UltraHydrating EnergyBoosting ...,4.6,8
3240,3240,18202,dermalogica PreCleanse Balm and Mitt,4.6,552
3241,3241,22247,Skin Inc Pure Serum Mist,4.9,11
3242,3242,27101,Clinique Repairwear Uplifting Firming Cream fo...,4.2,154
3243,3243,27101,Clinique Repairwear Uplifting Firming Cream fo...,4.2,276

In [5]:
df.describe()

        Unnamed: 0         price        stars          vote
count  3244.000000  3.244000e+03  3244.000000   3244.000000
mean   1621.500000  4.495740e+04     3.551418     80.162145
std     936.606463  6.421733e+04     1.830841    392.348852
min       0.000000  6.000000e+02     0.000000      0.000000
25%     810.750000  1.537000e+04     3.500000      1.000000
50%    1621.500000  2.629200e+04     4.400000     11.000000
75%    2432.250000  5.055100e+04     4.700000     55.000000
max    3243.000000  1.546868e+06     5.000000  13221.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3244 entries, 0 to 3243
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  3244 non-null   int64
 1   price       3244 non-null   int64
 2   title       3244 non-null   object
 3   stars       3244 non-null   float64
 4   vote        3244 non-null   int64
dtypes: float64(1), int64(3), object(1)
memory usage: 126.8+ KB

In [9]:
df['title'].unique()

array(['BeautyBio Rose Quartz Roller', 'Kopari Starry Eye Balm',
       'StriVectin SuperC Brighten  and  Correct Serum', ...,
       'Skin Inc Pure Serum Mist',
       'Clinique Repairwear Uplifting Firming Cream for Dry Skin',
       'Clinique Repairwear Uplifting Firming Cream for Combination Skin'],
      shape=(3208,), dtype=object)

In [10]:
df.nunique()

Unnamed: 0    3244
price          679
title         3208
stars           33
vote           410
dtype: int64

In [11]:
df.columns

Index(['Unnamed: 0', 'price', 'title', 'stars', 'vote'], dtype='object')

In [12]:
for col in df.columns:
    print(col)

Unnamed: 0
price
title
stars
vote

In [13]:
df.isnull()

      Unnamed: 0  price  title  stars   vote
0          False  False  False  False  False
1          False  False  False  False  False
2          False  False  False  False  False
3          False  False  False  False  False
4          False  False  False  False  False
...          ...    ...    ...    ...    ...
3239       False  False  False  False  False
3240       False  False  False  False  False
3241       False  False  False  False  False
3242       False  False  False  False  False
3243       False  False  False  False  False

[3244 rows x 5 columns]

In [14]:
df.isnull().sum()

Unnamed: 0    0
price         0
title         0
stars         0
vote          0
dtype: int64